- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.opencontrail.org"

- hosts: all
  roles:
    - contrail-common-libs2
    - configure-hosts-entries
    - role: setup-docker-registry
      when: setup_docker_registry == true

- hosts: all
  roles:
    - role: configure-hosts-entries
      hosts_entries:
        - fqdn: "{{ ansible_fqdn }}"
          address: "{{ ansible_all_ipv4_addresses[0] }}"

