- hosts: builder
  pre_tasks:
    - stat:
        path: "{{ ansible_env.HOME }}/rpmbuild/RPMS"
        register: rpmdir
  roles:
    - { role: packaging-fetch-el, when: rpmdir.stat.isdir is defined and rmpdir.stat.isdir }

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_pulp }}"

- hosts: "{{ site_pulp.fqdn }}"
  vars:
    reponame: "{{ zuul.change }}-{{ zuul.patchset }}"
    executor_package_dir: "{{ zuul.executor.work_root }}/packages"
  roles:
    - { role: packaging-publish-el, when: rpmdir.stat.isdir is defined and rpmdir.stat.isdir }
