- hosts: builder
  roles:
    - role: packaging-fetch-el

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_pulp }}"

- hosts: "{{ site_pulp.fqdn }}"
  vars:
    reponame: "{{ zuul.change }}-{{ zuul.patchset }}"
    executor_package_dir: "{{ zuul.executor.work_root }}/packages"
  roles:
    - role: packaging-publish-el

