- name: template the testbed.py
  template:
    src: testbed.py.j2
    dest: "{{ ansible_env.HOME}}/testbed.py"

- name: create the directory with repos
  file:
    path: "{{ ansible_env.HOME}}/mount"
    state: directory

- name: Clone contrail-test-ci repository
  git:
    repo: 'https://github.com/Juniper/contrail-test-ci'
    dest: "{{ ansible_env.HOME }}/mount/contrail-test-ci"

- name: Clone contrail-test repository
  git:
    repo: 'https://github.com/Juniper/contrail-test'
    dest: "{{ ansible_env.HOME }}/mount/contrail-test"

- name: Run the sanity test
  command: "{{ ansible_env.HOME }}/mount/contrail-test-ci/testrunner.sh run -t {{ ansible_env.HOME }}/testbed.py -m {{ ansible_env.HOME }}/mount -k /root/.ssh/id_rsa -f ci_sanity '{{ docker_registry.fqdn }}:{{ docker_registry.port }}/contrail-test:static-ocata'"
  become: yes

