- name: template the testbed.py
  template:
    src: testbed.py.j2
    dest: "{{ ansible_env.HOME}}/testbed.py"

- name: create the directory with repos
  file:
    path: "{{ ansible_env.HOME}}/mount"
    state: directory

- name: Clone contrail-test-ci repository
  git:
    repo: 'https://github.com/jluk-codi/contrail-test-ci'
    dest: "{{ ansible_env.HOME }}/mount/contrail-test-ci"

- name: Clone contrail-test-ci repository2
  git:
    repo: 'https://github.com/jluk-codi/contrail-test-ci'
    dest: "{{ ansible_env.HOME }}/contrail-test-ci"

- name: Clone contrail-test repository
  git:
    repo: 'https://github.com/Juniper/contrail-test'
    dest: "{{ ansible_env.HOME }}/mount/contrail-test"

- name: Copy empty config
  copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/testbed1.py"

- name: Run the sanity test
  command: "{{ ansible_env.HOME }}/contrail-test-ci/testrunner.sh run -t {{ ansible_env.HOME }}/testbed1.py -m {{ ansible_env.HOME }}/mount '10.84.56.38:5000/contrail-test:static-newton'"
  become: yes

- name: create the log directory on executor
  file:
    path: "{{ zuul.executor.log_root }}/sanity-logs"
    state: directory
  delegate_to: localhost

- name: Fetch the logs
  synchronize:
    src: "{{ ansible_env.HOME }}/contrail-test-runs"
    dest: "{{ zuul.executor.log_root }}/sanity-logs"
    mode: pull
    recursive: yes
