- name: template the testbed.py
  template:
    src: testbed.py.j2
    dest: "{{ ansible_env.HOME}}/testbed.py"

- name: run the testrunner container
  docker_container:
    image: 10.84.56.38:5000/contrail-test:static-newton
    command: date
