- name: template the testbed.py
  template:
    src: testbed.py.j2
    dest: "{{ ansible_env.HOME}}/testbed.py"

- name: Clone contrail-test-ci repository
  git:
    repo: 'https://github.com/Juniper/contrail-test-ci'
    dest: "{{ ansible_env.HOME }}/contrail-test-ci"

- name: Run the sanity test
  command: "{{ ansible_env.HOME }}/contrail-test-ci/testrunner.sh run -t {{ ansible_env.HOME }}/testbed.py"
