- name: Set variables
  set_fact:
    testrunner_image: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}/contrail-test:static-ocata"

- name: Template the testbed.py
  template:
    src: testbed.py.j2
    dest: "{{ ansible_env.HOME}}/testbed.py"

- name: Create the directory with repos
  file:
    path: "{{ ansible_env.HOME}}/mount"
    state: directory

# TODO Change this to zuul-merger prepared checkouts
# TODO Use packaged contrail-test when test container will be built in previous steps
- name: Clone test repositories
  git:
    repo: "https://github.com/Juniper/{{ item }}"
    dest: "{{ ansible_env.HOME }}/mount/{{ item }}"
  with_items:
    - contrail-test-ci
    - contrail-test

- name: Pull the testrunner image
  docker_image:
    name: "{{ testrunner_image }}"

- name: Run the sanity test
  command: "{{ ansible_env.HOME }}/mount/contrail-test-ci/testrunner.sh run -t {{ ansible_env.HOME }}/testbed.py -m {{ ansible_env.HOME }}/mount -k /root/.ssh/id_rsa -f ci_sanity '{{ testrunner_image }}'"
  become: yes
