- name: Set container build dir
  set_fact:
    docker_build_dir: "{{ ansible_env.HOME }}/contrail-container-builder"

- name: Clone contrail-container-builder repository
  git:
    repo: 'https://github.com/Juniper/contrail-container-builder/'
    force: yes
    dest: "{{ docker_build_dir }}"

- name: Prepare build configuration - common.env
  copy:
    content: |
      CONTRAIL_VERSION={{ zuul.change }}-{{ zuul.patchset }}
      CONTRAIL_REGISTRY={{ docker_registry.fqdn }}:{{ docker_registry.port }}
      CONTRAIL_REPOSITORY=http://{{ site_pulp.fqdn }}/pulp/repos/{{ zuul.change }}-{{ zuul.patchset }}
      OPENSTACK_VERSION={{ openstack_version }}
    dest: "{{ docker_build_dir }}/common.env"

- name: Prepare third party cache repo file
  copy:
    content: |
      [thirdpartycache]
      name=Contrail Third Party Cache
      baseurl=http://ci-repo.englab.juniper.net/pulp/repos/opencontrail-tpc/
      enabled=1
      gpgcheck=0
      priority=20
    dest: "{{ docker_build_dir }}/containers/base/tpc.repo"

- name: Prepare contrail repo file
  copy:
    content: |
      [contrail-{{ zuul.change }}-{{ zuul.patchset }}]
      name=Contrail {{ zuul.change }}-{{ zuul.patchset }}
      baseurl=http://{{ site_pulp.fqdn }}/pulp/repos/{{ zuul.change }}-{{ zuul.patchset }}
      enabled=1
      gpgcheck=0
      priority=10
    dest: "{{ docker_build_dir }}/containers/base/contrail.repo"

- name: Create log dir
  file:
    path: "{{ ansible_env.HOME }}/docker-logs"
    state: directory

- name: Build base containers
  include: build_container.yaml
  with_items:
    - base
    - analytics/base
    - controller/config/base
    - controller/control/base
    - controller/webui/base
    - test/base

- name: Build microservices
  include: build_container.yaml
  with_items:
    - agent/vrouter
    - agent/vrouter-init-kernel
    - analytics/alarm-gen
    - analytics/api
    - analytics/collector
    - analytics/query-engine
    - analytics/snmp-collector
    - analytics/topology
    - controller/config/api
    - controller/config/devicemgr
    - controller/config/schema
    - controller/config/svcmonitor
    - controller/control/control
    - controller/control/dns
    - controller/control/named
    - controller/webui/job
    - controller/webui/web
    - external/cassandra
    - external/cassandra-init
    - external/kafka
    - external/rabbitmq
    - external/rabbitmq-init
    - external/zookeeper
    - external/zookeeper-init
    - kubernetes/kube-manager
    - kubernetes/vrouter-init
    - nodemgr
    - openstack/compute-contrail-backend
    - openstack/neutron-contrail-backend
    - test/{{ openstack_version }}
