- hosts: all
  vars:
    openstack_version: newton
  pre_tasks:
    - name: Install build dependencies
      package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - docker
        - iproute
    - name: Configure docker insecure registries
      copy:
        content: |
          {
                  "insecure-registries": ["{{ docker_registry.fqdn }}:{{ docker_registry.port }}"]
          }
        dest: /etc/docker/daemon.json
      become: true
      become_user: root

    - name: Ensure that docker daemon is running
      service:
        name: docker
        state: started
      become: true
      become_user: root
    - name: pull and push webui-redis container
      shell: |
        docker pull {{ docker_registry.fqdn }}:{{ docker_registry.port }}/contrail-controller-webui-redis:4.1.0.0-8
        docker tag {{ docker_registry.fqdn }}:{{ docker_registry.port }}/contrail-controller-webui-redis:4.1.0.0-8 {{ docker_registry.fqdn }}:{{ docker_registry.port }}/contrail-controller-webui-redis:{{ zuul.change }}-{{ zuul.patchset }}-{{ openstack_version }}
        docker push {{ docker_registry.fqdn }}:{{ docker_registry.port }}/contrail-controller-webui-redis:{{ zuul.change }}-{{ zuul.patchset }}-{{ openstack_version }}
      become: true
  roles:
    - contrail-build-dockers
