- hosts: all
  roles:
    - role: contrail-ansible-deployer
      docker_provision_dir: '/tmp/contrail-container-deployer'
      contrail_version: "{{ zuul.change }}-{{ zuul.patchset }}"
      openstack_version: ocata
      deploy_kubernetes: True
