- hosts: all
  vars:
    openstack_version: newton
  pre_tasks:
    - name: Install build dependencies
      package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - docker
        - iproute

    - name: Configure docker insecure registries
      copy:
        content: |
          {
                  "insecure-registries": ["{{ docker_registry.fqdn }}:{{ docker_registry.port }}"]
          }
        dest: /etc/docker/daemon.json
      become: true
      become_user: root

    - name: Ensure that docker daemon is running
      service:
        name: docker
        state: started
      become: true
      become_user: root
    - name: pull and push webui-redis container
      shell: |
        docker pull 10.84.56.38:5000/contrail-controller-webui-redis:4.1.0.0-8
        docker tag 10.84.56.38:5000/contrail-controller-webui-redis:4.1.0.0-8 10.84.56.38:5000/contrail-controller-webui-redis:{{ zuul.change }}-{{ zuul.patchset }}-{{ openstack_version }}
        docker push 10.84.56.38:5000/contrail-controller-webui-redis:{{ zuul.change }}-{{ zuul.patchset }}-{{ openstack_version }}
      become: true
    - name: check for already built containers
      uri:
        url: http://{{ docker_registry.fqdn }}:{{ docker_registry.port }}/v2/contrail-base/manifests/{{ zuul.change }}-{{ zuul.patchset }}-{{ openstack_version }}
      ignore_errors: yes
      register: image_ready
    - name: Playbook exiting with SUCCESS because the containers are already built
      debug:
        msg: '0'
      when: image_ready.status == 200
    - name: exit if image exists
      meta: end_play
      when: image_ready.status == 200
  roles:
    - contrail-build-dockers
