- hosts: all
  vars:
    openstack_version: newton
  pre_tasks:
    - name: check for already built containers
      uri:
        url: http://{{ docker_registry.fqdn }}:{{ docker_registry.port }}/v2/contrail-base/manifests/{{ zuul.change }}-{{ zuul.patchset }}-{{ openstack_version }}
      ignore_errors: yes
      register: image_ready
    - name: Playbook exiting with SUCCESS because the containers are already built
      debug:
        msg: '0'
      when: image_ready.status == 200
    - name: exit if image exists
      meta: end_play
      when: image_ready.status == 200
  roles:
    - contrail-build-dockers
