- hosts: all
  roles:
    - role: contrail-ansible-deployer
      docker_provision_dir: '/tmp/contrail-container-deployer'
      contrail_version: "38333-2"
      openstack_version: newton
      deploy_kubernetes: False
    - contrail-sanitytests
