- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_pulp }}"

- hosts: "{{ site_pulp.fqdn }}"
  roles:
    - contrail-common-libs2
    - zuul-include-vars
    - setup-docker-registry2
