- name: Ensure that the orig tarball is present
  command: origtargz
  args:
    chdir: "{{ packaging.target_dir }}"

- name: Update apt repositories
  apt:
    update_cache: yes
  become: True
  become_user: root

- name: Install package dependencies for the build
  shell: |
    mk-build-deps -r -i debian/control \
      --tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes"
  args:
    chdir: "{{ packaging.target_dir }}"
  become: True
  become_user: root
  register: deps
  failed_when: "'mk-build-deps: Unable to install all build-dep packages' in deps.stdout"

- name: Create source and binary debian packages
  command: debuild --preserve-env -us -uc
  args:
    chdir: "{{ packaging.target_dir }}"
  environment:
    DEBFULLNAME: "OpenContrail Developers"
    DEBEMAIL: "dev@lists.opencontrail.org"
    DEB_BUILD_OPTIONS: "parallel={{ ansible_processor_vcpus }}"
    LC_ALL: "C"
