- name: Prepare packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"

- name: Add a repository with Contrail dependencies
  yum_repository:
    name: contrail-tpc
    description: Contrail third-party dependencies
    baseurl: http://10.84.56.38/repos/centos/7/
    gpgcheck: no
  become: True
  become_user: root

# waiting for merge (38098, 38099)
- name: Apply temporary patches for CentOS7.4
  patch:
    src: "{{ item.patch }}"
    basedir: "{{ ansible_env.HOME }}/{{ packaging.target_dir }}/{{ item.path }}"
    strip: 1
  with_items:
    - { patch: 'vrouter.patch', path: 'vrouter/' }
    - { patch: 'contrail_spec.patch', path: 'tools/packages/' }

- name: Copy dkms.conf.in into location expected by the spec file
  copy:
    src: dkms.conf.in
    dest: "{{ ansible_env.HOME }}/{{ packaging.target_dir }}/tools/packaging/rpm/contrail/dkms.conf.in"

