- name: create package dir on the executor
  file:
    path: "{{ zuul.executor.work_root }}/packages"
    state: directory
  delegate_to: localhost

- name: Get a list of package files
  find:
    paths: "{{ ansible_env.HOME }}/rpmbuild/RPMS"
    recurse: yes
    patterns:
      - '*.rpm'
  register: package_list

- name: send packages to the executor
  synchronize:
    src: "{{ item.path }}"
    dest: "{{ zuul.executor.work_root }}/packages/"
    mode: pull
  with_items: "{{ package_list.files }}"
