- name: Install build requirements with yum
  shell: yum-builddep -y tools/packages/rpm/contrail/contrail.spec
  args:
    chdir: "{{ ansible_env.HOME }}/{{ packaging.target_dir }}"
  become: True
  become_user: root

- name: Copy over the build script
  copy:
    src: build.sh
    dest: "{{ ansible_env.HOME }}/build.sh"
    mode: "0755"

- name: Execute the build script
  command: "bash {{ ansible_env.HOME }}/build.sh"
  args:
    chdir: "{{ packaging.target_dir }}"

