- name: Install build requirements with yum
  shell: yum-builddep -y tools/packages/rpm/contrail/contrail.spec
  args:
    chdir: "{{ ansible_env.HOME }}/{{ packaging.target_dir }}"
  become: True
  become_user: root

- name: Fetch third-party packages
  shell: python fetch_packages.py
  args:
    chdir: "{{ ansible_env.HOME }}/{{ packaging.target_dir }}/third_party/"

- name: Build binary & source packages for contrail-vnc
  shell: |
    rpmbuild --define '_sbtop {{ ansible_env.HOME }}/{{ packaging.target_dir }}' \
      --ba tools/packages/rpm/contrail/contrail.spec
  args:
    chdir: "{{ ansible_env.HOME }}/{{ packaging.target_dir }}"
  environment:
    SCONSFLAGS: "-j {{ ansible_processor_vcpus }} --opt=production"
