- hosts: all
  roles:
    - role: kolla-provision-dockers
      kolla_provision_dir: '/tmp/contrail-kolla-ansible'
      kolla_config_dir: "{{ kolla_provision_dir }}/etc/kolla"
      kolla_docker_distro: "ubuntu"
      openstack_version: "ocata"
      kolla_version: "{{ zuul.change }}-{{ zuul.patchset }}-{{ openstack_version }}"
    - role: contrail-ansible-deployer
      docker_provision_dir: '/tmp/contrail-container-deployer'
      contrail_version: "{{ zuul.change }}-{{ zuul.patchset }}"
      openstack_version: newton
      deploy_kubernetes: False
    - contrail-sanitytests
