- name: Create the log directory on executor
  file:
    path: "{{ zuul.executor.log_root }}/sanity-logs"
    state: directory
  delegate_to: localhost

- stat:
    path: "/root/contrail-test-runs"
  register: logdir
  become: true

- name: Fetch the logs
  synchronize:
    src: "/root/contrail-test-runs"
    dest: "{{ zuul.executor.log_root }}/sanity-logs"
    mode: pull
    recursive: yes
  when: logdir.stat.isdir is defined and logdir.stat.isdir
  become: true
